### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by MartinStokelj** [Liagson/ConcaveHullGenerator#3] opened 2019-09-23 07:37 UTC
Hi,
I am trying to use concavity diferent than 1 and I am getting error.
Points which I am using are here "dot_list" [points.txt](https://github.com/Liagson/ConcaveHullGenerator/files/3640990/points.txt)
Graphical image of points [points](https://user-images.githubusercontent.com/30079270/65408436-87605f00-dde5-11e9-9588-216be8ae8448.png)

	//geometry
	List<Position> lineCoordinates2 = new List<Position>();
	int scaleFactor = 1;
	double concavity = 0; 
	bool isSquareGrid = false;

	Hull.setConvHull(dot_list);
	Hull.setConcaveHull(Math.Round(Convert.ToDecimal(concavity), 2), scaleFactor, isSquareGrid);

	List<PointLatLng> coordinatesGeo = new List<PointLatLng>();
	for (var i = 0; i < Hull.hull_concave_edges.Count; i++)
	{
		for (var j = 0; j < Hull.hull_concave_edges[i].nodes.Length; j++)
		{
			PointLatLng myPosition = new PointLatLng(Hull.hull_concave_edges[i].nodes[j].x, Hull.hull_concave_edges[i].nodes[j].y);
			if (!coordinatesGeo.Contains(myPosition))
			{
				GPoint gp = MainForm.instance.gMapControl.FromLatLngToLocal(myPosition);
				int index = uav.getInsertIndex(coordinatesGeo, new Accord.Point(gp.X, gp.Y));
				if (index >= 0 && index <= coordinatesGeo.Count)
					coordinatesGeo.Insert(index, myPosition);
			}
		}
	}

What I am doing wrong? Is the Node id important and I need to set it? Currently it fix the error but it does not help to calculate correct points according to concavity.

It looks like something is wrong with calculation, because if I move points a littlebit it calculate ok.
Picture  [Example2](https://user-images.githubusercontent.com/30079270/65416559-6e14de00-ddf8-11e9-9f33-e1e9e735ce17.png)

**Comment by Liagson** [comment] 2019-09-23 19:33
Hmmmm, can you tell me the line where the exception is thrown? 

PS: I updated the code after noticing I, sadly, used type decimal for operations (they are now doubles)
Yes, I've edited this message many times, I really can't express my shame.

**Comment by MartinStokelj** [comment] 2019-09-24 07:20
I can still simulate exception, exception is thrown in function getHullNearbyNodes line
		

> currentID = concave_hull[line_count].nodes[position].id;

Exception is thrown if i do not set id of Nodes, calling
> dot_list.Add(new Node(wp.Lat, wp.Lng)); 
instead of
> dot_list.Add(new Node(wp.Lat, wp.Lng, dot_list.Count));

Even with new code (double fix) the concavity = 0.5 does not have correct effect.

![Example3](https://user-images.githubusercontent.com/30079270/65489622-d244aa00-deab-11e9-8820-e4ba15227f1e.png)

**Comment by Liagson** [comment] 2019-09-24 08:53
I fear the id is mandatory in order for the dots to be differentiated between each other. I need to check it when I have some free time, but I think I'll delete the (unused?) constructor with no id in order to avoid this issue. That being said, I will try to take a closer look to your problem soon.

By the way, I see this line in your code and I fear it is wrong:
`for (var j = 0; j < Hull.hull_concave_edges[i].nodes.Length; j++)`
That `Length` refers to the length (sort of, if you want the true length you will need to sqrt Length) of an edge, not to the nodes of an edge.

**Comment by MartinStokelj** [comment] 2019-09-24 09:14
To draw previous picture I used code from Init.cs, so my code is relevant to reported bug so you can ignore my code in first message.
If you want to simulate the bug where concavity  = 0.5 is not correctly display use my points from file in first message.

**Comment by Liagson** [comment] 2019-09-24 10:24
Looking at your file I see that you have "Num" and "id" variables (being the id variable always 0) Could that be the issue?

**Comment by MartinStokelj** [comment] 2019-09-24 11:04
Yes that was the problem that I got exception (like I explained in previos posts) since node id was not set. Now node id is set as num (id are set as sequntial numbers) and exception is gone, but concavity parameter 0,5 don't have correct result. 
As I can see the  concavity = 0.5 works only in some cases. I made new files and screenshot so you will be able to debug faster. 

Not working example:
image [NotWorking](https://user-images.githubusercontent.com/30079270/65506310-9588ab00-decb-11e9-8458-364ecc301307.png)
dot_list [NotWorking.txt](https://github.com/Liagson/ConcaveHullGenerator/files/3646807/NotWorking.txt)

Working example:
image [Works](https://user-images.githubusercontent.com/30079270/65506342-a3d6c700-decb-11e9-9adc-417fbaeb52b4.png)
dot_list [Working.txt](https://github.com/Liagson/ConcaveHullGenerator/files/3646809/Working.txt)

**Comment by Liagson** [comment] 2019-09-25 07:47
Can you show me how you pass the file data to dot_list? I've tried viewing how result but the coordinates are way too close (like 0.001 units close) to be shown clearly in the unity demo scene.

**Comment by MartinStokelj** [comment] 2019-09-25 09:43
I use C# for my code, I draw points on the map with GMap.Net library so this are real Latitude, Longitude coordinates and added them to dot_list,

	dot_list.Add(new Node(wp.Lat, wp.Lng, dot_list.Count));

 for your example I export them with

	for (var i = 0; i < dot_list.Count; i++)
		logger.Debug("id:" + dot_list[i].id + " x:" + dot_list[i].x + " y:" + dot_list[i].y);

Code to read file would be

    string location = "C://Downloads//Working.txt";
    string[] lines = File.ReadAllLines(location);
    for (var i = 0; i < lines.Length; i++)
    {
        if (string.IsNullOrEmpty(lines[i]))
            continue;
        string[] line = lines[i].Split(' ');
        int id = int.Parse(line[0].Split(':')[1]);
        double Lat = double.Parse(line[1].Split(':')[1]);
        double Lng = double.Parse(line[2].Split(':')[1]);
        dot_list.Add(new Node(Lat, Lng, id));
    }

I hope you needed the code to read file to dot_list or I didn't understood your last message.

**Comment by MartinStokelj** [comment] 2019-09-30 16:50
Did you already have had the opportunity to look for mistake in calculating concavity = 0.5?

**Comment by Liagson** [comment] 2019-09-30 17:24
I've been able to reproduce the error, but currently have no clue about the cause of it. With luck I'll have enough time this weekend to find the root of the problem 😖

**Comment by MartinStokelj** [comment] 2019-10-04 11:21
Ok great, thanks.

**Comment by Liagson** [comment] 2019-10-05 16:29
I think I've fixed it and as far as I see there are no bugs now **(*)** 
Major change that you need to bare in mind now: 

- **Concavity now makes sense:** setting concavity to _-1_ will be the same as saying you don't want concavities. Setting it to 1 will mean _extreme 0º angle concavities_ are possible (avoid setting it to 1). Concavity equals to the cosine of a concave angle. If you can confirm my new changes are working fine for you I will upload the new documentation as soon as I can (Explaining all this in detail). Setting concavity to 0.5 seems fine to me.
- **isSquareGrid** boolean is gone. The code always checks tangent lines.

**(*)**: By _fixed_ I mean I've redone pretty much everything because I couldn't understand my terrible legacy code.


![HullResults](https://user-images.githubusercontent.com/12009365/66257707-d1115800-e79c-11e9-9050-4bade074caa5.png)

**Comment by MartinStokelj** [comment] 2019-10-08 08:28
Hi again, did you even test it on my example points? This is even wors result then before...
[concavity05](https://user-images.githubusercontent.com/30079270/66379747-5a4fa700-e9b6-11e9-89f7-26b7c4ad6d84.png)
[concavity1](https://user-images.githubusercontent.com/30079270/66379748-5ae83d80-e9b6-11e9-83c2-28dbd13d6811.png)

**Comment by Liagson** [comment] 2019-10-08 08:33
Have you tried lowering the `concavity`? (Maybe to -0.5 or lower) or lowering the `scaleFactor`? That area, as far as I see, looks correct to me, but it looks like the concavity factor is too high/agressive

**Comment by MartinStokelj** [comment] 2019-10-08 08:35
I tested:
image concavity1
int scaleFactor = 1;
double concavity = 1;

image concavity05
int scaleFactor = 1;
double concavity = 0.5;

**Comment by Liagson** [comment] 2019-10-08 08:36
Try setting concavity to a negative value (it goes from -1 to 1)

**Comment by MartinStokelj** [comment] 2019-10-08 08:38
Ok that looks much better and I think now is ok
[concavity-1](https://user-images.githubusercontent.com/30079270/66380421-af3fed00-e9b7-11e9-8a80-993606e7d632.png)
[concavity-05](https://user-images.githubusercontent.com/30079270/66380423-af3fed00-e9b7-11e9-96b1-24ab3e207370.png)

**Comment by Liagson** [comment] 2019-10-08 08:43
Happy to see it working :)
I'll leave this Issue open just in case you find something weird with the new changes. I'm sorry about not updating my documentation (I'll try this weekend)

**Comment by MartinStokelj** [comment] 2019-10-08 08:45
I already asked this question in separate issue task but I didn't get the correct answer so I will try to ask differently.
Can you add a parameter for setting buffer, with buffer i would like to tell how much out of current point the new returned points should be.
I hope the image will explain
[bufferExample](https://user-images.githubusercontent.com/30079270/66381081-efec3600-e9b8-11e9-8e9b-99bc8e700405.png)

**Comment by Liagson** [comment] 2019-10-08 09:18
Can you create a separate issue for that enhancement (adding, if you can, more details)? I have a few questions regarding your suggestion, but I don't want to fill this thread with non bug-related replies 😅

**Comment by MartinStokelj** [comment] 2019-10-08 09:24
Ok I have reopend the issue. Thanks for help.

**Comment by Liagson** [comment] 2019-10-12 09:04
@MartinStokelj by the way, have you experienced a performance improvement with the last changes? I'm really curious about it.

**Comment by MartinStokelj** [comment] 2019-10-14 06:00
For my use all works ok, thank you again for the fix.

**Comment by Liagson** [comment] 2019-10-14 07:55
Nice. I'm closing this issue then :)

**Closed as completed by Liagson** 2019-10-14 07:55 UTC
Labels: bug
